### ISSUE TITLE
onSkip event not firing

### ISSUE THREAD

**Issue by shanemeetingsbooker** [xbsoftware/enjoyhint#102]
Hi, Im currently using this plugin to give users a guided tour of my application. I want to do something when the user presses the skip button however the event does not work. Works fine the onStart and onEnd event. Is the best way around this a custom event. Here is a look at my code. 

$(document).ready(function () {

                //initialize instance
                var enjoyhint_instance = new EnjoyHint({
                    onEnd: function () {
                        alert("done");                        
                    },

                    onStart: function () {
                        alert("start");
                        return;                        
                    },

                    onSkip: function () {
                        alert("skip");
                        return;                       
                    }
                });

**Comment by MehmetDemir42** [comment]
Same as well onSkip not firing

**Comment by MehmetDemir42** [comment]
Hi if you are editing enjoyhint.js with this, it will works like charms,

go to line 10 on options add this

,
onSkip:function(){}

and go to line 32 onSkipClick function edit like this,

onSkipClick: function (){
options.onSkip();
skipAll();
}

**Comment by zapper59** [comment]
Hi guys, those changes you just mentioned are in the master branch: https://github.com/xbsoftware/enjoyhint/blob/master/src/enjoyhint.js Are you perhaps using the npm package that hasn't been updated in 2 years?

**Comment by shanemeetingsbooker** [comment]
Hi zapper,

I am just pulling the hosted file from https://cdnjs.com/
https://cdnjs.cloudflare.com/ajax/libs/enjoyhint/3.1.0/enjoyhint.js

Is this not the most up to date version?

**Comment by zapper59** [comment]
This project is semi-abandoned so you're going to want to go with what's in github, or better yet this fork: https://github.com/darron1217/enjoyhint.js

Also where was that url documented? I don't see it in the readme

**Comment by shanemeetingsbooker** [comment]
Perfect I have used this version and everything works fine.

Thanks

**Comment by ShvedkaSvetka** [comment]
Hi @shanemeetingsbooker ,

Thank you for your question. Current version works without this issue. 
![2019-07-18_1742](https://user-images.githubusercontent.com/8545452/61466947-775e7600-a983-11e9-9802-a8c329786a60.png)
