### ISSUE TITLE
Close Button Task

### ISSUE THREAD

**Issue by emresaracoglu** [xbsoftware/enjoyhint#105]
Hi,

Thank you for this project.

I want to give a task to the close button, If the closing icon is clicked, I will be able to submit it with Ajax.
How do I get to the close icon?

Thank you.

**Comment by zapper59** [comment]
You're going to want to set an onEnd event handler.

**Comment by emresaracoglu** [comment]
Thank you. @zapper59

**Comment by emresaracoglu** [comment]
@zapper59 , 

Actually, I'm not talking about that.  

"Onend" for fires after the last step in script but this is what I'm talking about:
![screenshot_2018-08-31 backbone js todomvc](https://user-images.githubusercontent.com/297968/44914282-748d6f00-ad38-11e8-91a6-a5e417e35498.png)
Task when this button _(tour close button, not last step)_ is clicked

**Comment by zapper59** [comment]
Ah sorry. You should be able to set a click event handler on the "enjoyhint_close_btn" class.

**Comment by emresaracoglu** [comment]
Thank you @zapper59
