### ISSUE TITLE
Page not scrolling when Enjoy hint is below screen fold.

### ISSUE THREAD

**Issue by sohrabzia** [xbsoftware/enjoyhint#107]
I have long page in production. when hint is below screen fold hint is moving to the specific element but it is not scrolling page, which makes it not visible.

I have recreated the issue on codepen.
[Demo](https://codepen.io/sohrabzia/full/VGoeav/)

**Comment by junioranto2** [comment]
+1

**Comment by ozknemoy** [comment]
if i install enjoyhint from bower, i also have this issue. but npm package works diffrently.
my code for webpack:
```
import 'enjoyhint/jquery.enjoyhint';
import 'jquery.scrollto';
import * as EnjoyHint from 'enjoyhint'
window['EnjoyHint']  = EnjoyHint ; 
```

**Comment by claudiobr** [comment]
+1 . 
I realy need to manually install it, so, no NPM for me.

**Comment by ozknemoy** [comment]
you can use this pr https://github.com/xbsoftware/enjoyhint/pull/103
