### ISSUE TITLE
Bug on top right position

### ISSUE THREAD

**Issue by KoIIIeY** [xbsoftware/enjoyhint#30]
example - http://board.sa-wd.ru
when hint opened on "menu" button(step 12), arrow directed to the right, but I expect it will be directed to the left.

**Comment by michaelsking1993** [comment]
@KoIIIeY On step 2 of your build-a-board site, how did you get the arrow/message to point downwards?

**Comment by KoIIIeY** [comment]
Sorry, I don't remember now (

**Comment by michaelsking1993** [comment]
Do you remember if it was something custom that you did, or if it was a function built into the library?

**Comment by michaelsking1993** [comment]
Is there any way I could take a look at that code? I've been trying to get this to work for hours and hours 😆

**Comment by KoIIIeY** [comment]
Where was one strange thing ) In config I use <div style="width: 100px;">bla bla bla</div> - so I set width, and code start work as i need.

**Comment by KoIIIeY** [comment]
https://buildyourboard.pro/scripts/enjoyhint/enjoyhint-conf-en.js - check this config.
