### ISSUE TITLE
Enjoyhint in Wordpress

### ISSUE THREAD

**Issue by hanadullset** [xbsoftware/enjoyhint#4]
First off, thank you for making Enjoyhint available for free! 

I'm just learning javascript, so I'm learning as I go. I'm stuck as to where I would place the codes to make the overlay activate only on the home page?

Would there happen to be a Wordpress tutorial that I could check out? Or would you be able to advise where or how to place the code in my Wordpress site?

Thank you!

P.S. Not sure if this is the proper place to ask for help, GitHub is new to new as well. Apologizes in advance.

**Comment by ShvedkaSvetka** [comment]
Hello, thank you for taking time filling this issue!

Every issue should provide the necessary information for us to investigate. This explains why your issue has been closed. If you still have the issue, please create it again and provide information how to reproduce the issue.
