### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by sushrita001** [xbsoftware/enjoyhint#40]
After including enjoyhint.js in html, i am getting the error that "Uncaught ReferenceError: require is not defined". My application using NodeJS for backend and Angular and Jade for front end.
script(src="/enjoyHint/enjoyhint.min.js")

**Comment by devasur** [comment]
Turns out KineticJS decides client vs. server execution mode using the defined state of 'exports' variable.  After modifying the initialization routine a bit code worked fine.
