### ISSUE TITLE
This is an awesome library, anything similar in reactjs?

### ISSUE THREAD

**Issue by cliren** [xbsoftware/enjoyhint#45]
Would of great help if anyone can point me to a library similar to this built in reactJS!. Thanks in advance!

**Comment by joyfulelement** [comment]
+1

**Comment by VaskaDagamas** [comment]
+1

**Comment by kimmikirino** [comment]
+1

**Comment by prem911** [comment]
It would be awesome to get a react component for this.
+1

**Comment by ShvedkaSvetka** [comment]
Hi, thank you for the request. Right know we doesn't support react/js, but mybe in near feauture we will add support for the library.
