### ISSUE TITLE
Vertical touch scroll issue

### ISSUE THREAD

**Issue by dalidovski** [xbsoftware/enjoyhint#48]
It would be nice if you help me!

After instantiate enjoyhint using `window.enjoyhint_instance.run();` the vertical swipe (scroll) is not working yet using angular-touch.js (the horizontal swipe still working fine).

I'm using:
- AngularJS v1.4.7
- jQuery v2.1.0

Thank you!

**Comment by mejriyassine** [comment]
Dear,

I had same issue, and after investigations, looks like the plugin is locking touch event so you need to remove `$(document).on("touchmove",lockTouch);` Line 25
In enjoyhint.js
https://github.com/xbsoftware/enjoyhint/blob/master/enjoyhint.js

I hope it works for you

**Comment by dalidovski** [comment]
Thanks, It works !
