### ISSUE TITLE
non-standards events [help wanted]

### ISSUE THREAD

**Issue by lfreneda** [xbsoftware/enjoyhint#52]
somebody could help me out with non-standards events samples using 'custom' and  enjoyhint_instance.trigger('custom_event_name'); ?

**Comment by lfreneda** [comment]
got it, forget about it :dancer:

**Comment by mayashavin** [comment]
Hi, if you wish to use custom event, you can do like the example below:
`{
          onBeforeStart: function(){
//Here you assign/trigger the event to the proper selector
$('#selector').click(function(e){
enjoyhint_instance.trigger('custom_event_name');
})         
          },
          selector:'#selector',
          event:'custom_event_name',
          event_type:'custom',
          description:'Do Something.',
        }`

Hope it helps.

**Comment by lfreneda** [comment]
Thanks sz
