### ISSUE TITLE
JavaScript runtime error: Unable to get property 'left' of undefined or null reference in enjoyhint.js

### ISSUE THREAD

**Issue by priyankkeshri** [xbsoftware/enjoyhint#58]
In runtime this error is coming. "JavaScript runtime error: Unable to get property 'left' of undefined or null reference"

Can you help me regarding this.

Thanks in advance
With regards
Priyank Keshri

**Comment by AllSeeingEye** [comment]
Basically this means that EnjoyHint can't find one of the elements that you've listed in the steps list. Can you post (part of) your configuration object?

**Comment by andrewspy** [comment]
I am facing the same issue here. May I know if EnjoyHint is compatible with web component standard, as I am using it inside `<template>` tag. Thanks!

**Comment by ShvedkaSvetka** [comment]
Hello, thank you for taking time filling this issue!

Every issue should provide the necessary information for us to investigate. This explains why your issue has been closed. If you still have the issue, please create it again and provide information how to reproduce the issue.
