### ISSUE TITLE
problem $body.enjoyhint is not a function

### ISSUE THREAD

**Issue by KaueSantos** [xbsoftware/enjoyhint#61]
Hello guys, i'm trying to apply interactive tutorials in my web application. I decided to use enjoyHInt. But on my first test i received the error below.
I just make the initial steps. So i do:

1st import (it's ok);
2nd ctrl + c / ctrl + v in the script provided by "https://github.com/xbsoftware/enjoyhint"
3º i created a div and a button with class especified on the code js.

And  i started my web application and i received this error on my console:

VM1533 enjoyhint.js: 22 Uncaught TypeError: $ body.enjoyhint is not a function
At init (VM1533 enjoyhint.js: 22)
At new EnjoyHint (VM1686 enjoyhint.js: 173)
At VM1536 Cad119Action! Browser.action: 364

Do you have somthing to help me?

full code: 
<html>
	<head>

		<link rel="stylesheet" href="enjoyhint/enjoyhint/jquery.enjoyhint.css" type="text/css">
		<script type="text/javascript" src="enjoyhint/enjoyhint/enjoyhint.js"></script>
		<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>

		<title>Teste Framework</title>
	</head>

	<style>
		.new_btn{
			width: 50px;
			height: 50px;
			margin-top: 99px;
		}
	</style>

		
	<body>
		<div class="pendenciasTeste">
		<button class="new_btn" onclick="teste();"></button>
		</div>
	</body>
<script>
var teste = function(){
	
	alert("cliquei");
}

//initialize instance
var enjoyhint_instance = new EnjoyHint({});

//simple config. 
//Only one step - highlighting(with description) "New" button 
//hide EnjoyHint after a click on the button.
var enjoyhint_script_steps = [
  {
    'click .new_btn' : 'Click the "New" button to start creating your project'
  }  
];

//set script config
enjoyhint_instance.set(enjoyhint_script_steps);

//run Enjoyhint script
enjoyhint_instance.run();
</script>
</html>

//initialize instance
var enjoyhint_instance = new EnjoyHint({});

//simple config. 
//Only one step - highlighting(with description) "New" button 
//hide EnjoyHint after a click on the button.
var enjoyhint_script_steps = [
  {
    'click .new_btn' : 'Click the "New" button to start creating your project'
  }  
];

//set script config
enjoyhint_instance.set(enjoyhint_script_steps);

//run Enjoyhint script
enjoyhint_instance.run();
</script>
</html>

**Comment by Erdou** [comment]
I used download and put it in a `<script>` way (like legacy JS), worked well.
Now that I'm using Webpack w/ Yarn I've got the same issue. Weird thing is that I don't see $body.enjoyhint set somewhere

**Comment by davidsonsns** [comment]
I added **enjoyhint** with **yarn**, in my [**create-react-app**](https://github.com/facebookincubator/create-react-app).
To work I did the following:

```js
import 'jquery'
import 'enjoyhint / jquery.enjoyhint'
import 'enjoyhint'
```
