### ISSUE TITLE
Uncaught ReferenceError: EnjoyHint is not defined

### ISSUE THREAD

**Issue by theromie** [xbsoftware/enjoyhint#68]
I am using Enjoyhint with cookies when cookies are stored then no "Uncaught ReferenceError: EnjoyHint is not defined" but when i am deleting cookies is showing above error.
`if (cookie.indexOf('visited=', 0) == -1) {            
        document.cookie = "visited=1;expires=30 June 2035 23:59:59 GMT ;path=/";        
        setTimeout(function () {
            var enjoyhint_instance = new EnjoyHint({});
            var enjoyhint_script_steps = [
                {
                    'next .tour_sidebar' : 'Filter your search by locations, spors, specific dates, price, days and categories'
                },  
                {
                    "next .collections_wrap": "Check out our curated collections"
                }
            ];
            enjoyhint_instance.set(enjoyhint_script_steps);

            //run Enjoyhint script
            enjoyhint_instance.run();
        }, 2000);            
    }`

**Comment by acharkizakaria** [comment]
@theromie have you fixed this issue ?

**Comment by theromie** [comment]
nope i remove this script

**Comment by acharkizakaria** [comment]
Thanks for your intervention, it's ok now, I just forgot to include the "enjoyhint.js" file...

Good luck.
