### ISSUE TITLE
error after closing tour

### ISSUE THREAD

**Issue by Clickmari** [xbsoftware/enjoyhint#72]
Hi,

always after closing the tour with X or after finishing I'm getting a _'Cannot read property 'getBoundingClientRect' of undefined'_ (or rather '_substr of undefined_')  error in the browsers console. Did I miss something?

EDIT: it appears whenever I resize the window. I also tried that in another prototype, where enjoyhint is the only js I use. maybe you should remove the window.resize event handler after the tour is finished.

It seems as if the script is still looking for prev/forward buttons, doesn't find it and that causes the script to stop (?!). Anybody any idea how this is possible? As far as I can see (and possibly my basic understanding is'n enough), destroyEnjoy() should prevent that and it seems as if nobody else has a similar problem ... maybe.

:)

**Comment by spyke01** [comment]
I am also experiencing this issue on print as well.

**Comment by jzabate** [comment]
I also experience the same issue. Every time I close the tour. Any update on this?

**Comment by ezosher** [comment]
Same here any fix ?

![chrome_KodliCxCpw](https://user-images.githubusercontent.com/27009587/59336049-814ae480-8d06-11e9-8e42-87d782cef9db.png)

**Comment by ShvedkaSvetka** [comment]
Hi, it happend, becuase you used browser, where [getBoundingClientRect ](https://caniuse.com/#feat=getboundingclientrect)didn't supported.
