### ISSUE TITLE
Scroll not working anymore on latest version of chrome

### ISSUE THREAD

**Issue by trenoncourt** [xbsoftware/enjoyhint#73]
Scroll not working anymore on latest version of chrome.

I'm on version 62.0.3202.94

**Comment by rajendrav1989** [comment]
Scrolling is not working in Latest chrome browser.

Version 62.0.3202.94 (Official Build) (64-bit)

**Comment by itgrockv** [comment]
TypeError: $(...).scrollTo is not a function
Google Chrome version 63.0.3239.84

**Comment by davidsonsns** [comment]
$(...).scrollTo not exist, only **$(...).scrollTop**

**Comment by manushimjani** [comment]
Hello,

Any solutions to this would be very much helpful.

Thanks.

**Comment by davidsonsns** [comment]
I sent a pull request. But this repo is no longer being maintained.
If you want to adjust on your own go to the directory `node_modules`, in the folder of `enjoyhint` file `enjoyhint.js` and change line `136`:

Check the commits:
[https://github.com/xbsoftware/enjoyhint/pull/80/files](https://github.com/xbsoftware/enjoyhint/pull/80/files)

**Comment by darron1217** [comment]
@blackazaru Did this commit included in latest published npm version?
It's seems not resolved yet...

**Comment by darron1217** [comment]
I forked this repo and solved scrolling issue
https://github.com/darron1217/enjoyhint.js

**Comment by sujoykroy** [comment]
Updating jquery.scrollTo to "2.1.2" in bower.json and running "grunt" solved the issue for me.
