### ISSUE TITLE
Sustained

### ISSUE THREAD

**Issue by davidsonsns** [xbsoftware/enjoyhint#79]
Is this project still being maintained?

**Comment by nevf** [comment]
From the comments [here,](https://github.com/xbsoftware/enjoyhint/issues/59), no.

I was thinking of using Enjoyhint in our Webapp Clibu but after reading through the issues and seeing it appears to be dead I'm not going to. 

Also Kinetic.js which enjoyhint uses is dead and has been superseded by a much smaller library.

And size is another issue, with Enjoyhint up around 170KB unzipped which is big, considering what it does. Kinetic.js is the main problem here.

**Comment by darron1217** [comment]
I forked this repo and started fixing issues :)
https://github.com/darron1217/enjoyhint.js

**Comment by ShvedkaSvetka** [comment]
Hi @davidsonsns, we resumed development.
