### ISSUE TITLE
localStorage.setItem not working correctly?

### ISSUE THREAD

**Issue by MichaelEC** [xbsoftware/enjoyhint#92]
Hello,

I'm trying to get a second hint to appear once the same page refreshes after completing the first hint - here's the code snippet;

**This is the first hint, which works perfectly.**

```
var wasShown = 'enjoyhint:wasShownLocation';
var showNewHome = 'enjoyhint:showNewHome';
var showHomeLoc = 'enjoyhint:showHomeLoc';

if (localStorage.getItem(wasShown)) {

} else {

	var enjoyhint_script_steps = [
	{
		'next #Test1' : 'Some Text1'
	},
	{
		'click #Test2' : 'Some Text2',
		'shape' : 'rect',
	}
		];
	localStorage.setItem(wasShown, true);
	localStorage.setItem(showNewHome, true);
	localStorage.setItem(showHomeLoc, true);
}
enjoyhint_instance.set(enjoyhint_script_steps);
enjoyhint_instance.run();
</script>
```

**Then this is the second hint which needs to run after the first one has completed.**

```
<script>
var enjoyhint_instance = new EnjoyHint({});
var showHomeLoc = 'enjoyhint:showHomeLoc';

if (localStorage.getItem(showHomeLoc) !== "true" )
 {
 }
 else {
	 var enjoyhint_script_steps = [
	{
	 'click #Test3' : 'Some Text 3'
	}
	];
}
enjoyhint_instance.set(enjoyhint_script_steps);
enjoyhint_instance.run();
localStorage.setItem(showHomeLoc, false);
</script>
```
My logic was that, once the first hint has run, it'll set the second hint to 'True' which would then display 'Some Text 3' after that has finished it then sets the second hint to 'False' meaning it won't run again although this doesn't work as expected - any ideas?

**Comment by MichaelEC** [comment]
Nevermind, got it working shortly after!

Just had to add an onBeforeStart function to the first hint to make the other hint enabled before it runs, so after it runs it can disable itself - if you're curious the code was

`onBeforeStart:function(){
      localStorage.setItem(showHomeLoc, true);
    }`

**Comment by ShvedkaSvetka** [comment]
Hi @MichaelE,
enjoyhint doesn't use localStorage, but thank you for the question
