### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by Bykiev** [xbsoftware/enjoyhint#97]
CasinoHand font used by enjoyhint is not supporting cyrillic characters

**Comment by zapper59** [comment]
To use a custom font you can set a style on 
`.enjoy_hint_label{
font-family: '....'
}`

Just from a quick search, here are some similar fonts for cyrillic characters.
https://localfonts.eu/freefonts/handwritten-cyrillic-free-fonts/alcotton/

**Comment by Bykiev** [comment]
@zapper59, thanks!
You can close this issue.
